use sindicato;

INSERT INTO servicios(id, nombre) VALUES
(1,'AJUAR DE VARON'),
(2,'AJUAR DE NENA'),
(3,'CAJA NAVIDEÑA'),
(4,'CARNET CAMPING Y PILETAS'),
(5,'GUARDAPOLVOS'),
(6,'KIT ESCOLAR'),
(7,'LENTES RECETADOS DE CERCA'),
(8,'LENTES RECETADOS DE LEJOS'),
(9,'MOCHILAS'),
(10,'REINTEGROS DE COMERCIOS'),
(11,'REINTEGROS DE CUOTA SIND/ADIC'),
(12,'REINTEGROS MEDICOS'),
(13,'REINTEGROS VARIOS'),
(14,'SEPELIOS'),
(15,'SUBSIDIO MINITURISMO/ PESCA')

